[application]

[web.app]

# HTML title tag content
title = "hear_buds"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
# Unique reverse-domain ID used for app bundles (including Android applicationId).
identifier = "com.fhenskens.hearbuds"
publisher = "fhenskens"
category = "Utility"
short_description = "Real-time hearing assist app with low-latency DSP."

